include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # 네이밍 규칙
    camel_case_types: true
    camel_case_extensions: true
    non_constant_identifier_names: false # 변수/함수는 lowerCamelCase 권장
    constant_identifier_names: true # 상수는 SCREAMING_SNAKE_CASE 허용

    # 코드 스타일
    prefer_single_quotes: true
    always_use_package_imports: true
    unnecessary_this: false
    prefer_final_locals: true
    avoid_print: true

    # 포맷팅 관련
    lines_longer_than_80_chars: false # 100자까지 허용

    # 불필요한 코드 방지
    avoid_unused_constructor_parameters: true
    avoid_init_to_null: true
    unnecessary_null_in_if_null_operators: true
    avoid_redundant_argument_values: true

    # 안전성
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    unnecessary_const: true

    # 기타
    directives_ordering: true
    sort_constructors_first: true
    avoid_function_literals_in_foreach_calls: true
